// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz43pFuXamR2ovi6n9ys9qGRMFG8s3gLs',
    appId: '1:436788658506:web:1d91b40ceabd8b41a8c1b3',
    messagingSenderId: '436788658506',
    projectId: 'zenstay-b3dc4',
    authDomain: 'zenstay-b3dc4.firebaseapp.com',
    storageBucket: 'zenstay-b3dc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd48n0yTcCck7de-pIjz-dbYeYVtZJMMI',
    appId: '1:436788658506:android:99e9b5ada4a9868ba8c1b3',
    messagingSenderId: '436788658506',
    projectId: 'zenstay-b3dc4',
    storageBucket: 'zenstay-b3dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx0wAH3fpiC2KuCSvl1RzknsyKztaelOk',
    appId: '1:436788658506:ios:e999ca559f1ec221a8c1b3',
    messagingSenderId: '436788658506',
    projectId: 'zenstay-b3dc4',
    storageBucket: 'zenstay-b3dc4.firebasestorage.app',
    iosBundleId: 'com.zenthora.zenstay',
  );
}
